FROM tensorflow/tensorflow:latest-gpu

RUN apt-get update && apt-get install software-properties-common -y
RUN cd /usr/lib/python3/dist-packages && cp apt_pkg.cpython-310-x86_64-linux-gnu.so apt_pkg.so
RUN add-apt-repository -y ppa:openjdk-r/ppa && apt-get update && apt-get install -y openjdk-8-jdk

ADD requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
